# Generated by Django 4.2.2 on 2023-07-03 10:01

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="customers/", verbose_name="Photo"
            ),
        ),
    ]
